create table kmeans_data (
	id text null,
	cnpj text null,
	name text null,
	revenue text null,
	profit_margin text null,
	recurrence text null,
	product text null,
	city text null,
	state text null,
	region text null,
	segment text null,
	sector text null,
	vehicles text null,
	employees text null,
	age text null,
	company_size text null);